stages:
  - test
  - deploy

default:
  image: python:3.9-slim
  before_script:
    - apt update
    - apt install -y make
    - pip install poetry
    - poetry config virtualenvs.in-project false
    - poetry install

pytest:
  stage: test
  script:
    - poetry run pytest tests --cov=src --cov-report term-missing
    - poetry run python3 -m coverage report
    - poetry run python3 -m coverage html -d coverage
    - poetry run python3 -m coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    expose_as: coverage
    paths:
      - coverage/
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  tags:
    - no-gpu
    - GenuineIntel


document:
  stage: deploy
  script:
    - make document
  artifacts:
    paths:
      - public
  only:
    - main
    - develop
    - fix_sphinx
    