stateDiagram
    direction LR
    state "funcB" as state_0
    state "funcA" as state_1
    state "funcD" as state_2
    state "funcC" as state_3
    state_0 --> [*]
    [*] --> state_1
    state_1 --> state_0: Pipe
    state_1 --> state_3: Pipe
    state_2 --> [*]
    state_3 --> state_2: Pipe