name: github pages

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    container:
        image: python:3.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Setup
        shell: bash
        run: |
        apt update -y
        apt install -y make
        pip install poetry
        poetry config virtualenvs.in-project false
        poetry install

      - name: docs
        shell: bash
        run: |
          make document

      - name: deploy_pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          force_orphan: true
